# Importações

In [1]:
import pandas as pd
import os
import numpy as np
from sqlalchemy import text
from sqlalchemy import create_engine

PRPI_DATABASE_URL = os.getenv("PRPI_DATABASE_URL")
engine = create_engine(PRPI_DATABASE_URL)

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.set_option("display.max_colwidth", None)

# Carregamento de dados e pré transformações

## Produções Técnicas

In [2]:
query = "select * from cnpq_producaotecnica order by tipo_pub asc;"
producoes_tecnicas_df = pd.read_sql(query, engine)

producoes_tecnicas_df = producoes_tecnicas_df.rename(columns={
    "id": "ID",
    "curriculo_id": "ID do Currículo",
    "sequencia": "Sequência",
    "titulo": "Título",
    "ano": "Ano",
    "pais": "País",
    "idioma": "Idioma",
    "flag_relevancia": "Relevância",
    "doi": "DOI",
    "tipo_pub": "Tipo de Publicação",
    "informacao_adicional_id": "ID de Informação Adicional"
})

### Padronização de Tipo de Publicação

In [3]:
producoes_tecnicas_df["Tipo de Publicação"] = (
    producoes_tecnicas_df["Tipo de Publicação"]
        .str.replace("-", " ", regex=False)
        .str.lower()
        .str.replace("cao", "ção", regex=False)
        .str.title()
)

## Membros de Projetos

In [4]:
query = """
  SELECT
  pr.id AS projeto_id,
  pr.titulo AS titulo_projeto,
  p.nome AS nome_pessoa,
  p.email AS email_pessoa,
  uo.nome AS campus,
  CASE
      WHEN p.email ILIKE '%@aluno.ifce.edu.br' THEN 'Discente'
      WHEN s.eh_docente = TRUE THEN 'Docente'
      WHEN s.eh_tecnico_administrativo = TRUE THEN 'TAE'
      ELSE NULL
  END AS categoria_funcional,
  pp.vinculo,
  pp.ativo,
  pr.inicio_execucao,
  EXTRACT(YEAR FROM pr.inicio_execucao) AS ano_inicio_execucao,
  pr.area_conhecimento_id,
  ac.descricao AS descricao_area_conhecimento,
  pr.edital_id,
  pe.titulo AS titulo_edital,
  pe.tipo_edital,
  -- Descrição do tipo do edital
  CASE pe.tipo_edital
      WHEN '1' THEN 'Pesquisa'
      WHEN '2' THEN 'Inovação'
      WHEN '3' THEN 'Pesquisa/Inovação - Contínuo'
      ELSE 'Desconhecido'
  END AS descricao_tipo_edital
FROM pesquisa_projeto pr
JOIN pesquisa_participacao pp
  ON pp.projeto_id = pr.id
JOIN unidadeorganizacional uo
  ON uo.id = pr.uo_id
JOIN comum_vinculo cv
  ON cv.id = pp.vinculo_pessoa_id
JOIN pessoa p
  ON p.id = cv.pessoa_id
LEFT JOIN servidor s
  ON s.pessoa_fisica_id = p.id
LEFT JOIN rh_areaconhecimento ac
  ON ac.id = pr.area_conhecimento_id
LEFT JOIN pesquisa_edital pe
  ON pe.id = pr.edital_id
ORDER BY pr.id, p.nome;
"""

with engine.connect() as conn:
    membros_projetos_df = pd.read_sql(text(query), conn)
    
membros_projetos_df = membros_projetos_df.rename(columns={
    "projeto_id": "ID do Projeto",
    "titulo_projeto": "Título do Projeto",
    "nome_pessoa": "Nome do Membro",
    "email_pessoa": "Email do Membro",
    "campus": "Campus",
    "categoria_funcional": "Categoria do Membro",
    "vinculo": "Vínculo com Projeto",
    "ativo": "Ativo",
    "inicio_execucao": "Início da Execução",
    "ano_inicio_execucao": "Ano de Início da Execução",
    "area_conhecimento_id": "ID da Área de Conhecimento",
    "descricao_area_conhecimento": "Área de Conhecimento",
    "edital_id": "ID do Edital",
    "titulo_edital": "Título do Edital",
    "tipo_edital": "ID do Tipo de Edital",
    "descricao_tipo_edital": "Tipo de Edital"
})

### Padronização de Edital

In [5]:
membros_projetos_df["Título do Edital"] = membros_projetos_df["Título do Edital"].str.upper()

conditions = [
    membros_projetos_df["Título do Edital"].str.startswith("PROGRAMA DE INICIAÇÃO CIENTÍFICA E TECNOLÓGICA VOLUNTÁRIA", na=False),
    membros_projetos_df["Título do Edital"].str.startswith("PIBITI", na=False),
    membros_projetos_df["Título do Edital"].str.startswith("PIBIC JR AF", na=False),
    membros_projetos_df["Título do Edital"].str.startswith("PIBIC JR", na=False),
    membros_projetos_df["Título do Edital"].str.startswith("PIBIC AF", na=False),
    membros_projetos_df["Título do Edital"].str.startswith("PIBIC", na=False),
]

choices = [
    "PICTV",
    "PIBITI",
    "PIBIC JR AF",
    "PIBIC JR",
    "PIBIC AF",
    "PIBIC",
]

membros_projetos_df["Edital"] = np.select(conditions, choices, default="FOMENTO EXTERNO")
membros_projetos_df = membros_projetos_df[membros_projetos_df["Título do Edital"] != "."]

### Padronização da Categoria do Membro

In [6]:
membros_projetos_df[["Categoria do Membro"]] = (
    membros_projetos_df[["Categoria do Membro"]]
        .fillna("Não Informado")
)

### Vinculo de Pesquisadores

In [7]:
vinculo_pesquisadores_df = membros_projetos_df

vinculo_pesquisadores_df["Tem Bolsista"] = vinculo_pesquisadores_df["Vínculo com Projeto"].eq("Bolsista")
vinculo_pesquisadores_df["Tem Voluntario"] = vinculo_pesquisadores_df["Vínculo com Projeto"].eq("Voluntário")

vinculo_pesquisadores_df = (
    vinculo_pesquisadores_df.groupby(["Nome do Membro", "Categoria do Membro"]).agg({
          "Tem Bolsista": "max",
          "Tem Voluntario": "max"
      })
      .reset_index()
)

vinculo_pesquisadores_df["Tipo de Participação"] = (
    vinculo_pesquisadores_df["Tem Bolsista"].map({True: "Bolsista", False: ""}) +
    vinculo_pesquisadores_df["Tem Voluntario"].map({True: "Voluntário", False: ""})
).str.replace("BolsistaVoluntário", "Bolsista e Voluntário")

display(vinculo_pesquisadores_df)

                                           Nome do Membro Categoria do Membro  \
0                                ANA LETÍCIA ARAUJO NUNES            Discente
1                         ANTÔNIO HEITOR MARTINS VALENTIM            Discente
2                         ARTHUR HERBSTER FERNANDES VOGEL            Discente
3                              Aaron Keven Ferreira Rocha            Discente
4                            Aaron Vinicius Souza Angelim            Discente
5                                   Abdias Araujo Bezerra            Discente
6                                       Abigail Luz Nobre       Não Informado
7                     Abimaell Jonathan Siqueira de Souza            Discente
8                                Abner Jose Girao Meneses             Docente
9                                   Abraão Alves da Silva            Discente
10                      Abraão Barbosa do Nascimento Lima            Discente
11                              Adalberto Viana Rodrigues             Docente
12                   Adam Ishael Correia Lima Verde Gomes            Discente
13                                Adeildo Cabral da Silva             Docente
14                            Adele Cristina Braga Araujo             Docente
15                                 Ademar Parente Alencar             Docente
16                      Adenilson Arcanjo de Moura Junior             Docente
17                   Aderaldo Irineu Levartoski de Araujo             Docente
18                                    Adina Alves de Lima            Discente
19                                       Adna Viana Dutra             Docente
20                            Adolfo Atila Cabral Moreira             Docente
21                            Adonias Caetano de Oliveira             Docente
22                                 Adria Lívia Lima Silva            Discente
23                           Adria Romenia Maciel da Cruz            Discente
24                                 Adriana Alves da Silva             Docente
25                              Adriana Maria de Oliveira            Discente
26                               Adriana Teixeira Pereira             Docente
27                             Adriana Thays Araujo Alves             Docente
28                                Adriano Barros Carneiro             Docente
29                                Adriano Holanda Pereira             Docente
30                                  Adriano Leal de Brito             Docente
31                              Adriano Monteiro da Silva                 TAE
32                             Adriano Tavares de Freitas             Docente
33                                  Adriel Holanda Santos            Discente
34                                    Adriele Silva Rocha            Discente
35                             Adrieli Moreira de Almeida            Discente
36                               Adrissa Figueiro Moreira             Docente
37                                   Aelton Biasi Giroldo             Docente
38                       Afonso José Moreira Barros Filho            Discente
39                                  Agebson Rocha Facanha             Docente
40                                Aglair Alves dos Santos            Discente
41                               Aglis Bernadino da Silva            Discente
42                             Aglis Pablo de Sousa Paiva            Discente
43                         Agni Lavínia Pinheiro Santiago            Discente
44                                   Aislan Pontes Santos            Discente
45                             Aislane Rodrigues de Sousa             Docente
46                             Ajalmar Rego da Rocha Neto             Docente
47                                Akauan Almeida Pinheiro            Discente
48                                   Alailton Alves Gomes            Discente
49                                    Alan Bezerra Torres             Docente
50                        Alan Cristian Silva de Oliveira            Discente
51                                   Alan Magalhaes Braga             Docente
52                                   Alan Robson da Silva            Discente
53                             Alana Jade de Lima Bezerra             Docente
54                          Alana Julia Silveira de Souza            Discente
55                       Alana Késsia Bandeira Cavalcante            Discente
56                              Alana Maria Ventura Silva       Não Informado
57                          Aldemir Girão da Silva Junior            Discente
58                              Aldimar Machado Rodrigues             Docente
59                             Aldisio Goncalves Medeiros                 TAE
60                                       Aldo Inácio Cruz       Não Informado
61                            Alef Kaua Pinheiro da Silva            Discente
62                       Alejandro Augusto Leandro Moraes            Discente
63                                  Alessa Mendes de Lima            Discente
64                                  Alex Cabral de Britto             Docente
65                            Alex Carlos Rodrigues Alves             Docente
66                                   Alex Holanda Dourado             Docente
67                                     Alex Lacerda Ramos             Docente
68                          Alex Lazaro de Sousa Nogueira            Discente
69                            Alex Samyr Mesquita Barbosa             Docente
70                          Alex Wesley de Carvalho Alves            Discente
71                                 Alex de Lucena Furtado            Discente
72                               Alexander Viana Prudente            Discente
73                         Alexandre Augusto Alves Guedes             Docente
74                          Alexandre Caio Monteiro Silva            Discente
75                       Alexandre Carreira da Cruz Sousa             Docente
76                                 Alexandre Landim Felix             Docente
77                               Alexandre Magalhaes Lima            Discente
78                         Alexandre Magno Ferreira Diniz             Docente
79                         Alexandre Nery Diógenes Freire            Discente
80                      Alexandre Reuber Almeida da Silva             Docente
81                  Alexandre da Costa Sombra de Oliveira            Discente
82                             Alexandre dos Santos Silva            Discente
83                               Alexandro Lima Damasceno             Docente
84                    Alexia Francisca Araujo de Santiago            Discente
85                        Alexsandra Erissa Maia da Silva            Discente
86                             Alexsandra Sombra Lourenco             Docente
87                              Alexsandro Costa da Silva            Discente
88                           Alexsandro Ferreira da Silva            Discente
89                               Alice Emanuelly da Silva            Discente
90                                   Alice Holanda Santos            Discente
91                                 Alice Petronilio Sousa            Discente
92                                   Alice da Silva Sousa            Discente
93                                   Alice da Silva Sousa       Não Informado
94                              Alicia de Araújo Oliveira            Discente
95                                    Aline Barbosa Alves            Discente
96                                 Aline Batista da Silva            Discente
97                                   Aline Braga da Silva             Docente
98                              Aline Luiza de Sousa Lima            Discente
99                                Aline Maria Brito Lucas             Docente
100                            Aline Maria Silva de Moura            Discente
101                                     Aline Mendes Mota            Discente
102                                  Aline Nonato Pereira            Discente
103                                  Aline Silva Quaresma             Docente
104                            Aline de Carvalho Oliveira             Docente
105                                  Aline de Melo Freire            Discente
106             Alisandra Cavalcante Fernandes de Almeida             Docente
107                               Alisson Aurélio Sérvolo            Discente
108                               Alisson Aurélio Sérvolo       Não Informado
109                               Alisson Chaves Ferreira            Discente
110                              Alisson Germano de Sousa            Discente
111                          Alisson Medeiros de Oliveira             Docente
112                                Alisson Romeu de Sousa            Discente
113                   Alisson Sampaio de Carvalho Alencar             Docente
114                                  Allan Brito Teixeira            Discente
115                          Allan Henrique de Lima Brito            Discente
116                             Allan Kaio da Costa Silva            Discente
117                                   Allan da Silva Maia             Docente
118                             Allana Joyce Soares Gomes             Docente
119                                Allyson Bonetti Franca             Docente
120                        Alvaro Guilherme de Lima Sousa            Discente
121                          Alyandra Ribeiro de Oliveira            Discente
122                      Alyne Danielle Rodrigues Parente            Discente
123                    Alysson Henrique de Souza Pinheiro            Discente
124                                 Alysson Matos Barbosa            Discente
125                              Alzeir Machado Rodrigues             Docente
126                           Amalia Maria Maciel Justino            Discente
127                                Amanda Coelho do Carmo            Discente
128                                Amanda Conrado Pereira             Docente
129                          Amanda Emilly Amorim Pereira            Discente
130                              Amanda Galdino Negreiros            Discente
131                              Amanda Gonçalves Alboino            Discente
132                           Amanda Kelly Moreira Maciel            Discente
133                        Amanda Larissa Castelo Barbosa            Discente
134                                   Amanda Lima Ribeiro            Discente
135                                     Amanda Maia Silva            Discente
136                         Amanda Mazza Cruz de Oliveira             Docente
137                            Amanda Paulino Viana Pinto            Discente
138                          Amanda Raquel Guerreiro Maia            Discente
139                        Amanda Raquel Rodrigues Pessoa             Docente
140                          Amanda Resenhe Dias Siqueira            Discente
141                                 Amanda Rodrigues Leal             Docente
142                            Amanda Vitória Gomes Viana            Discente
143                            Amanda Vitória Gomes Viana       Não Informado
144                            Amanda de Farias Rodrigues            Discente
145                                 Amanda de Sales Paiva            Discente
146                                 Amanda de Souza Silva            Discente
147                      Amarilio Goncalves Coelho Junior             Docente
148                      Amarilio Gonçalves Coelho Júnior            Discente
149                        Amauri Holanda de Souza Junior             Docente
150                             Ambrosio Martins da Cunha             Docente
151                              Ana Amelia Neri Oliveira             Docente
152                      Ana Amelia Rodrigues de Oliveira             Docente
153                            Ana Beatriz Araujo Tavares            Discente
154                     Ana Beatriz Nascimento dos Santos            Discente
155                 Ana Beatriz Nottingham Nibon da Silva            Discente
156                              Ana Beatriz Nôbre Barros            Discente
157                        Ana Beatriz Rodrigues da Silva            Discente
158                       Ana Beatriz de Vasconcelos Lima            Discente
159                   Ana Carenina de Albuquerque Ximenes             Docente
160                           Ana Carla Carneiro da Silva            Discente
161                                Ana Carla Gomes Amorim            Discente
162                                  Ana Carla Lima Paula            Discente
163                                Ana Carla Silva Freire            Discente
164                              Ana Carla da Silva Vidal            Discente
165                             Ana Carolina Barbosa Lima            Discente
166                          Ana Carolina Firmino Ribeiro            Discente
167              Ana Carolina Marcal Pires Ferreira Lucas             Docente
168                      Ana Carolina Oliveira dos Santos            Discente
169                         Ana Carolina Ribeiro de Sousa            Discente
170                              Ana Carolina Sales Viana            Discente
171                      Ana Carolina Silva do Nascimento            Discente
172                             Ana Caroline Bento Santos            Discente
173                                Ana Cecilia Costa Lima            Discente
174                              Ana Cecília Moreira Mota            Discente
175                           Ana Celia Eufrasio da Ponte            Discente
176                           Ana Clara Alvares von Linde            Discente
177                                 Ana Clara Gomes Alves            Discente
178                                 Ana Clara Souza Silva            Discente
179                              Ana Clarice Rocha Araujo            Discente
180                         Ana Clarisse Rodrigues Arruda            Discente
181                          Ana Claudia Gouveia de Sousa             Docente
182                         Ana Claudia Mendonca Pinheiro             Docente
183                          Ana Claudia dos Santos Silva             Docente
184                    Ana Claúdia Nascimento dos Santos             Discente
185                              Ana Cristina Andre Felix            Discente
186                                 Ana Cristina da Rocha            Discente
187                             Ana Daiane Costa da Silva            Discente
188                           Ana Elen dos Santos Batista            Discente
189                        Ana Gabriele Cunha Souza Alves            Discente
190                         Ana Gabrielle Brandão de Lima            Discente
191                          Ana Gabrielly Santiago Moura            Discente
192                          Ana Hevelin Peixoto Ferreira            Discente
193                             Ana Ingrid Felix da Silva            Discente
194                  Ana Isabel Ribeiro Porto de Oliveira       Não Informado
195                           Ana Jaqueline Barbosa Sales            Discente
196                             Ana Jasmim Messias Moura             Discente
197                          Ana Julia Goncalves de Sousa            Discente
198                               Ana Julia Regis Ribeiro            Discente
199                               Ana Júlia Alves Germano            Discente
200                              Ana Kalyne de Lima Sousa            Discente
201                              Ana Karina Pereira Costa            Discente
202                              Ana Karine Pessoa Bastos             Docente
203                        Ana Karine Portela Vasconcelos             Docente
204                           Ana Karla Rodrigues Sampaio            Discente
205                               Ana Karolina Sousa Lima            Discente
206                         Ana Karoline Pinheiro Bezerra            Discente
207                        Ana Karoline Rocha de Oliveira            Discente
208                            Ana Laricia Faustino de Sa            Discente
209                             Ana Leticia Sobral Coelho            Discente
210                            Ana Leticia Sousa da Silva            Discente
211                             Ana Letícia Viana de Melo            Discente
212                                  Ana Liria Cruz Lopes            Discente
213                             Ana Louíza Oliveira Costa       Não Informado
214                               Ana Lucia Moura Andrade             Docente
215                           Ana Luisa Cavalcante Farias            Discente
216                          Ana Luisa de Farias Oliveira            Discente
217                              Ana Luiza Rodrigues Lima            Discente
218                                      Ana Luzia Araujo            Discente
219                           Ana Lídia Lisboa de Andrade            Discente
220                               Ana Lívia Bandeira Amed            Discente
221                                Ana Lívia Maciel Rocha            Discente
222                           Ana Maria Alves de Oliveira            Discente
223                             Ana Maria Graciano Freire            Discente
224                               Ana Maria Lima Saldanha            Discente
225                           Ana Maria de Abreu Siqueira             Docente
226                             Ana Maria de Lima Ribeiro            Discente
227                                     Ana Márcia Araújo            Discente
228                                Ana Odete Dantas Sousa            Discente
229                      Ana Paula Almeida Bertossi Souza             Docente
230                              Ana Paula Aquino Benigno             Docente
231                           Ana Paula Bezerra de Araujo             Docente
232                          Ana Paula Peixoto dos Santos            Discente
233                              Ana Paula da Silva Lopes            Discente
234                             Ana Paula de Almeida Lima            Discente
235                         Ana Quézia Avelino de Queiroz            Discente
236                             Ana Quézia Lima Junqueiro            Discente
237                                Ana Rachel Lima Bonfim            Discente
238                            Ana Raquel Araujo da Silva                 TAE
239                             Ana Sheila Gomes de Brito            Discente
240                                 Ana Sofia Sousa Matos            Discente
241                      Ana Thamires de Morais Rodrigues            Discente
242                              Ana Valessa Mota Lustosa            Discente
243          Ana Valquiria Vasconcelos da Fonseca Brandao             Docente
244                   Ana Victoria Honorato do Nascimento            Discente
245                           Ana Virginia de Sousa Rocha                 TAE
246                             Ana Vitória Azevedo Braga            Discente
247                  Ana Vitória Barros Vieira dos Santos            Discente
248                             Ana Vitória de Sousa Lima            Discente
249               Anahi Geovana Alves Rodrigues Gonçalves            Discente
250                                Analice Araujo de Lima            Discente
251                              Ananda Amorim de Meneses            Discente
252                        Anastacio Ferreira de Oliveira             Docente
253                                 Anaxagoras Maia Girao             Docente
254                          Anderson Alan da Cruz Coelho             Docente

## Projetos de Pesquisa

In [8]:
query = """
SELECT DISTINCT
 projeto.id AS cod_projeto,
 projeto.titulo AS titulo_projeto,
 uo.nome AS campus,
 projeto.aprovado, 
 projeto.inicio_execucao,
 EXTRACT(YEAR FROM projeto.inicio_execucao) AS ano_inicio_execucao,
 projeto.fim_execucao,
 EXTRACT(YEAR FROM projeto.fim_execucao) AS ano_fim_execucao,
 projeto.data_finalizacao_conclusao,
 gp.descricao as grupo_pesquisa_nome,
 ac.descricao as area_conhecimento,
 COALESCE(ac_superior.descricao, ac.descricao) AS grande_area_conhecimento,
 projeto.edital_id,
 edital.titulo AS titulo_edital,
 edital.tipo_edital as tipo_edital_id,
 CASE
     WHEN edital.tipo_edital = '1' THEN 'PESQUISA'
     WHEN edital.tipo_edital = '2' THEN 'INOVACAO'
     WHEN edital.tipo_edital = '3' THEN 'PESQUISA_INOVACAO_CONTINUO'
     WHEN edital.tipo_edital = '4' THEN 'EXTENSAO_FLUXO_CONTINUO'
     ELSE 'DESCONHECIDO'
 END AS descricao_tipo_edital 
FROM
 pesquisa_projeto projeto
JOIN
 pesquisa_edital edital ON projeto.edital_id = edital.id
LEFT JOIN
 cnpq_grupopesquisa gp ON projeto.grupo_pesquisa_id = gp.id
LEFT JOIN
 rh_areaconhecimento ac ON projeto.area_conhecimento_id = ac.id
LEFT JOIN
 rh_areaconhecimento ac_superior ON ac.superior_id = ac_superior.id
LEFT JOIN 
 unidadeorganizacional uo ON uo.id = projeto.uo_id
ORDER BY
 cod_projeto ASC;
"""

with engine.connect() as conn:
    projetos_df = pd.read_sql(text(query), conn)

projetos_df = projetos_df.rename(columns={
     "cod_projeto": "ID do Projeto",
    "titulo_projeto": "Título do Projeto",
    "campus": "Campus",
    "aprovado": "Aprovado",
    "inicio_execucao": "Início da Execução",
    "ano_inicio_execucao": "Ano de Início da Execução",
    "fim_execucao": "Fim da Execução",
    "ano_fim_execucao": "Ano de Fim da Execução",
    "grupo_pesquisa_nome": "Nome do Grupo de Pesquisa",
    "area_conhecimento": "Área de Conhecimento",
    "edital_id": "ID do Edital",
    "titulo_edital": "Título do Edital",
    "tipo_edital_id": "ID do Tipo de Edital",
    "descricao_tipo_edital": "Tipo de Edital",
    "grande_area_conhecimento": "Grande Área de Conhecimento",
    "data_finalizacao_conclusao": "Data de Finalização da Conclusão"
})

### Padronização de Campus do Projeto

In [9]:
projetos_df["Campus"] = projetos_df["Campus"].str.replace("CAMPUS ", "", regex=False)
projetos_df["Campus"] = projetos_df["Campus"].str.replace("AVANÇADO DE ", "", regex=False)

display(projetos_df["Campus"].unique())

<StringArray>
[         'REITORIA',         'FORTALEZA',           'QUIXADA',
           'CRATEUS',           'TIANGUA',         'ITAPIPOCA',
 'LIMOEIRO DO NORTE',            'IGUATU',           'CAMOCIM',
 'JUAZEIRO DO NORTE',            'ACARAU',         'MARACANAÚ',
            'SOBRAL',          'BATURITE',        'MARANGUAPE',
           'CAUCAIA',             'CEDRO',         'HORIZONTE',
         ' ACOPIARA',           'ARACATI',       'MORADA NOVA',
           'UBAJARA',         'JAGUARIBE',             'PECÉM',
              'TAUA',           'CANINDE',             'CRATO',
         'TABULEIRO',          'PARACURU',        'BOA VIAGEM',
            'UMIRIM',      'GUARAMIRANGA',        'JAGUARUANA',
           'MOMBAÇA']
Length: 34, dtype: str

### Situação do Projeto

In [10]:
conditions = [
    projetos_df["Aprovado"] == False,
    projetos_df["Data de Finalização da Conclusão"].isna()
]

choices = ["Não Aprovado", "Em Execução"]

projetos_df["Situação do Projeto"] = np.select(
    conditions,
    choices,
    default="Concluído"
)

### Padronização de Título do Projeto

In [11]:
projetos_df['Título do Projeto'] = (
    projetos_df['Título do Projeto']
    .astype(str)
    .str.strip()
    .str.title()
    .str.replace(r'\s+', ' ', regex=True)
)

### Padronização de Edital

In [12]:
projetos_df["Título do Edital"] = projetos_df["Título do Edital"].str.upper()

conditions = [
    projetos_df["Título do Edital"].str.startswith("PROGRAMA DE INICIAÇÃO CIENTÍFICA E TECNOLÓGICA VOLUNTÁRIA", na=False),
    projetos_df["Título do Edital"].str.startswith("PIBITI", na=False),
    projetos_df["Título do Edital"].str.startswith("PIBIC JR AF", na=False),
    projetos_df["Título do Edital"].str.startswith("PIBIC JR", na=False),
    projetos_df["Título do Edital"].str.startswith("PIBIC AF", na=False),
    projetos_df["Título do Edital"].str.startswith("PIBIC", na=False),
]

choices = [
    "PICTV",
    "PIBITI",
    "PIBIC JR AF",
    "PIBIC JR",
    "PIBIC AF",
    "PIBIC",
]

projetos_df["Edital"] = np.select(conditions, choices, default="FOMENTO EXTERNO")
projetos_df = projetos_df[projetos_df["Título do Edital"] != "."]

## Projetos Aprovados por Grupo de Pesquisa

In [13]:
query = """
SELECT 
    gp.id as grupo_pesquisa_id,
    gp.descricao as grupo_pesquisa_nome,
    COUNT(*) AS total
FROM pesquisa_projeto as pp
JOIN cnpq_grupopesquisa as gp
	ON pp.grupo_pesquisa_id = gp.id
WHERE aprovado = TRUE
GROUP BY gp.id, gp.descricao
ORDER BY gp.id;
"""

with engine.connect() as conn:
    grupos_pesquisa_df = pd.read_sql(text(query), conn)

grupos_pesquisa_df = grupos_pesquisa_df.rename(columns={
    "grupo_pesquisa_id": "ID do Grupo de Pesquisa",
    "grupo_pesquisa_nome": "Nome do Grupo de Pesquisa",
    "total": "Total de Projetos Aprovados"
})

# Geral ✅

## Estatísticas

In [17]:
total_projetos = projetos_df["Título do Projeto"].nunique()
total_projetos_aprovados = projetos_df[projetos_df["Aprovado"] == True].shape[0]
total_areas_conhecimento = projetos_df["Área de Conhecimento"].nunique()
total_grupos_de_pesquisa = projetos_df["Nome do Grupo de Pesquisa"].nunique()
total_patentes = producoes_tecnicas_df[producoes_tecnicas_df["Tipo de Publicação"] == "Patente"].shape[0]
total_producoes_tecnicas = producoes_tecnicas_df.shape[0]

print(f"Total de Projetos: {total_projetos}")
print(f"Total de Projetos Aprovados: {total_projetos_aprovados}")
print(f"Total de Áreas de Conhecimento: {total_areas_conhecimento}")
print(f"Total de Grupos de Pesquisa: {total_grupos_de_pesquisa}")
print(f"Total de Patentes: {total_patentes}")
print(f"Total de Produções Técnicas: {total_producoes_tecnicas}")

Total de Projetos: 2856
Total de Projetos Aprovados: 1811
Total de Áreas de Conhecimento: 66
Total de Grupos de Pesquisa: 195
Total de Patentes: 544
Total de Produções Técnicas: 82496

## Pesquisadores

In [18]:
total_pesquisadores = vinculo_pesquisadores_df["Nome do Membro"].count()
print(f"Total de Pesquisadores: {total_pesquisadores}")

analise_pesquisadores = vinculo_pesquisadores_df.groupby("Categoria do Membro").agg(
    total_pesquisadores=('Nome do Membro', 'count'),
    bolsistas=('Tipo de Participação', lambda x: (x == 'Bolsista').sum()),
    voluntarios=('Tipo de Participação', lambda x: (x == 'Voluntário').sum()),
    bolsistas_voluntarios=('Tipo de Participação', lambda x: (x == 'Bolsista e Voluntário').sum())
).reset_index().rename(columns={'total_pesquisadores': 'Total de Pesquisadores', 'bolsistas': 'Bolsistas', 'voluntarios': 'Voluntários', 'bolsistas_voluntarios': 'Bolsistas e Voluntários'})

analise_pesquisadores = analise_pesquisadores.sort_values(by="Total de Pesquisadores", ascending=False)

analise_pesquisadores['Bolsistas'] = (
    analise_pesquisadores['Bolsistas'].astype(str) +
    ' (' + (analise_pesquisadores['Bolsistas'] / analise_pesquisadores['Total de Pesquisadores'] * 100).round(2).astype(str) + '%)'
)

analise_pesquisadores['Voluntários'] = (
    analise_pesquisadores['Voluntários'].astype(str) +
    ' (' + (analise_pesquisadores['Voluntários'] / analise_pesquisadores['Total de Pesquisadores'] * 100).round(2).astype(str) + '%)'
)

analise_pesquisadores['Bolsistas e Voluntários'] = (
    analise_pesquisadores['Bolsistas e Voluntários'].astype(str) +
    ' (' + (analise_pesquisadores['Bolsistas e Voluntários'] / analise_pesquisadores['Total de Pesquisadores'] * 100).round(2).astype(str) + '%)'
)

display(analise_pesquisadores)

Total de Pesquisadores: 3390

,Categoria do Membro,Total de Pesquisadores,Bolsistas,Voluntários,Bolsistas e Voluntários
0,Discente,2211,1136 (51.38%),910 (41.16%),165 (7.46%)
1,Docente,1006,51 (5.07%),777 (77.24%),178 (17.69%)
3,TAE,94,34 (36.17%),52 (55.32%),8 (8.51%)
2,Não Informado,79,28 (35.44%),48 (60.76%),3 (3.8%)

# Projetos Por Grande Área ✅

## Projetos por Grande Área

In [ ]:
analise_grande_area = projetos_df.groupby("Grande Área de Conhecimento").agg(
    total_projetos=("ID do Projeto", "count")
).reset_index().rename(columns={"total_projetos": "Total de Projetos"}).sort_values(by="Total de Projetos", ascending=False)

analise_grande_area['Total de Projetos'] = (
    analise_grande_area['Total de Projetos'].astype(str) + 
    ' (' + (analise_grande_area['Total de Projetos'] / analise_grande_area['Total de Projetos'].sum() * 100).round(2).astype(str) + '%)'
)

display(analise_grande_area)

   Grande Área de Conhecimento Total de Projetos
3   CIÊNCIAS EXATAS E DA TERRA       840 (24.9%)
6                  ENGENHARIAS      686 (20.33%)
0            CIÊNCIAS AGRÁRIAS      624 (18.49%)
8             MULTIDISCIPLINAR       302 (8.95%)
4             CIÊNCIAS HUMANAS       294 (8.71%)
7  LINGUÍSTICA, LETRAS E ARTES       178 (5.28%)
2            CIÊNCIAS DA SAÚDE       168 (4.98%)
1          CIÊNCIAS BIOLÓGICAS       143 (4.24%)
5   CIÊNCIAS SOCIAIS APLICADAS       139 (4.12%)

## Grande Área por Ano

In [ ]:
analise_grande_area_por_ano = projetos_df.groupby("Grande Área de Conhecimento").agg(
    total_2022=("Ano de Início da Execução", lambda x: (x == 2022).sum()),
    total_2023=("Ano de Início da Execução", lambda x: (x == 2023).sum()),
    total_2024=("Ano de Início da Execução", lambda x: (x == 2024).sum()),
    total_2025=("Ano de Início da Execução", lambda x: (x == 2025).sum()),
    total_2026=("Ano de Início da Execução", lambda x: (x == 2026).sum())
).reset_index().rename(columns={"total_2026": "2026", "total_2025": "2025", "total_2024": "2024", "total_2023": "2023", "total_2022": "2022"})

display(analise_grande_area_por_ano)

   Grande Área de Conhecimento  2022  2023  2024  2025  2026
0            CIÊNCIAS AGRÁRIAS     0   180   202   231    10
1          CIÊNCIAS BIOLÓGICAS     0    37    37    62     7
2            CIÊNCIAS DA SAÚDE     0    47    56    63     2
3   CIÊNCIAS EXATAS E DA TERRA     1   244   265   312    18
4             CIÊNCIAS HUMANAS     0    75    75   138     6
5   CIÊNCIAS SOCIAIS APLICADAS     2    38    32    65     2
6                  ENGENHARIAS     1   215   218   245     7
7  LINGUÍSTICA, LETRAS E ARTES     0    55    47    72     4
8             MULTIDISCIPLINAR     1    80    79   138     4

## Situação de Projetos por Campus

In [ ]:
analise_projetos_por_campus = projetos_df.groupby("Campus").agg(
    total_projetos=("ID do Projeto", "count"),
    concluidos=("Situação do Projeto", lambda x: (x == "Concluído").sum()),
    em_execucao=("Situação do Projeto", lambda x: (x == "Em Execução").sum()),
    nao_aprovados=("Situação do Projeto", lambda x: (x == "Não Aprovado").sum())
).reset_index().rename(columns={"total_projetos": "Total de Projetos", "concluidos": "Concluídos", "em_execucao": "Em Execução", "nao_aprovados": "Não Aprovados"})

analise_projetos_por_campus = analise_projetos_por_campus.sort_values(by="Total de Projetos", ascending=False)

analise_projetos_por_campus['Concluídos'] = (
    analise_projetos_por_campus['Concluídos'].astype(str) +
    ' (' + (analise_projetos_por_campus['Concluídos'] / analise_projetos_por_campus['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

analise_projetos_por_campus['Em Execução'] = (
    analise_projetos_por_campus['Em Execução'].astype(str) +
    ' (' + (analise_projetos_por_campus['Em Execução'] / analise_projetos_por_campus['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

analise_projetos_por_campus['Não Aprovados'] = (
    analise_projetos_por_campus['Não Aprovados'].astype(str) +
    ' (' + (analise_projetos_por_campus['Não Aprovados'] / analise_projetos_por_campus['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

display(analise_projetos_por_campus)

## Grande Área por Campus

In [ ]:
analise_grande_area_por_campus = projetos_df.groupby("Campus").agg(
    total_projetos=("ID do Projeto", "count"),
    total_ciências_exatas_e_terra=("Grande Área de Conhecimento", lambda x: (x == "CIÊNCIAS EXATAS E DA TERRA").sum()),
    total_ciências_biologicas=("Grande Área de Conhecimento", lambda x: (x == "CIÊNCIAS BIOLÓGICAS").sum()),    
    total_ciências_humanas=("Grande Área de Conhecimento", lambda x: (x == "CIÊNCIAS HUMANAS").sum()),
    total_ciências_sociais_aplicadas=("Grande Área de Conhecimento", lambda x: (x == "CIÊNCIAS SOCIAIS APLICADAS").sum()),
    total_engenharia=("Grande Área de Conhecimento", lambda x: (x == "ENGENHARIAS").sum()),
    total_agrarias=("Grande Área de Conhecimento", lambda x: (x == "CIÊNCIAS AGRÁRIAS").sum()),
    total_saude=("Grande Área de Conhecimento", lambda x: (x == "CIÊNCIAS DA SAÚDE").sum()),
    total_multidisciplinar=("Grande Área de Conhecimento", lambda x: (x == "MULTIDISCIPLINAR").sum()),
    total_linguistica=("Grande Área de Conhecimento", lambda x: (x == "LINGUÍSTICA, LETRAS E ARTES").sum())
).reset_index().rename(columns={
    "total_projetos": "Total de Projetos", 
    "total_ciências_exatas_e_terra": "Ciências Exatas e da Terra", 
    "total_ciências_biologicas": "Ciências Biológicas", 
    "total_ciências_humanas": "Ciências Humanas", 
    "total_ciências_sociais_aplicadas": "Ciências Sociais Aplicadas", 
    "total_engenharia": "Engenharia", 
    "total_agrarias": "Ciências Agrárias", 
    "total_saude": "Ciências da Saúde", 
    "total_multidisciplinar": "Multidisciplinar",
    "total_linguistica": "Linguística, Letras e Artes"
})

analise_grande_area_por_campus = analise_grande_area_por_campus.sort_values(by="Total de Projetos", ascending=False)

analise_grande_area_por_campus['Ciências Exatas e da Terra'] = (
    analise_grande_area_por_campus['Ciências Exatas e da Terra'].astype(str) +
    ' (' + (analise_grande_area_por_campus['Ciências Exatas e da Terra'] / analise_grande_area_por_campus['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

analise_grande_area_por_campus['Ciências Biológicas'] = (
    analise_grande_area_por_campus['Ciências Biológicas'].astype(str) +
    ' (' + (analise_grande_area_por_campus['Ciências Biológicas'] / analise_grande_area_por_campus['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

analise_grande_area_por_campus['Ciências Humanas'] = (
    analise_grande_area_por_campus['Ciências Humanas'].astype(str) +
    ' (' + (analise_grande_area_por_campus['Ciências Humanas'] / analise_grande_area_por_campus['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

analise_grande_area_por_campus['Ciências Sociais Aplicadas'] = (
    analise_grande_area_por_campus['Ciências Sociais Aplicadas'].astype(str) +
    ' (' + (analise_grande_area_por_campus['Ciências Sociais Aplicadas'] / analise_grande_area_por_campus['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)   

analise_grande_area_por_campus['Engenharia'] = (
    analise_grande_area_por_campus['Engenharia'].astype(str) +
    ' (' + (analise_grande_area_por_campus['Engenharia'] / analise_grande_area_por_campus['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

analise_grande_area_por_campus['Ciências Agrárias'] = (
    analise_grande_area_por_campus['Ciências Agrárias'].astype(str) +
    ' (' + (analise_grande_area_por_campus['Ciências Agrárias'] / analise_grande_area_por_campus['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

analise_grande_area_por_campus['Ciências da Saúde'] = (
    analise_grande_area_por_campus['Ciências da Saúde'].astype(str) +
    ' (' + (analise_grande_area_por_campus['Ciências da Saúde'] / analise_grande_area_por_campus['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

analise_grande_area_por_campus['Multidisciplinar'] = (
    analise_grande_area_por_campus['Multidisciplinar'].astype(str) +
    ' (' + (analise_grande_area_por_campus['Multidisciplinar'] / analise_grande_area_por_campus['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

analise_grande_area_por_campus['Linguística, Letras e Artes'] = (
    analise_grande_area_por_campus['Linguística, Letras e Artes'].astype(str) +
    ' (' + (analise_grande_area_por_campus['Linguística, Letras e Artes'] / analise_grande_area_por_campus['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

display(analise_grande_area_por_campus)

,Campus,Total de Projetos,Ciências Exatas e da Terra,Ciências Biológicas,Ciências Humanas,Ciências Sociais Aplicadas,Engenharia,Ciências Agrárias,Ciências da Saúde,Multidisciplinar,"Linguística, Letras e Artes"
11,FORTALEZA,362,74 (20.44%),5 (1.38%),30 (8.29%),13 (3.59%),167 (46.13%),10 (2.76%),18 (4.97%),25 (6.91%),20 (5.52%)
19,LIMOEIRO DO NORTE,329,29 (8.81%),2 (0.61%),32 (9.73%),5 (1.52%),51 (15.5%),125 (37.99%),46 (13.98%),12 (3.65%),27 (8.21%)
28,SOBRAL,210,9 (4.29%),7 (3.33%),4 (1.9%),5 (2.38%),28 (13.33%),139 (66.19%),1 (0.48%),15 (7.14%),2 (0.95%)
20,MARACANAÚ,194,83 (42.78%),0 (0.0%),1 (0.52%),0 (0.0%),48 (24.74%),4 (2.06%),0 (0.0%),57 (29.38%),1 (0.52%)
26,QUIXADA,191,52 (27.23%),0 (0.0%),32 (16.75%),24 (12.57%),69 (36.13%),0 (0.0%),0 (0.0%),14 (7.33%),0 (0.0%)
14,IGUATU,167,59 (35.33%),1 (0.6%),32 (19.16%),17 (10.18%),1 (0.6%),36 (21.56%),6 (3.59%),14 (8.38%),1 (0.6%)
31,TIANGUA,138,74 (53.62%),0 (0.0%),6 (4.35%),2 (1.45%),0 (0.0%),41 (29.71%),3 (2.17%),2 (1.45%),10 (7.25%)
18,JUAZEIRO DO NORTE,136,10 (7.35%),10 (7.35%),2 (1.47%),2 (1.47%),55 (40.44%),10 (7.35%),25 (18.38%),22 (16.18%),0 (0.0%)
6,CANINDE,133,36 (27.07%),0 (0.0%),30 (22.56%),4 (3.01%),13 (9.77%),0 (0.0%),37 (27.82%),8 (6.02%),5 (3.76%)
10,CRATO,118,7 (5.93%),1 (0.85%),8 (6.78%),0 (0.0%),3 (2.54%),78 (66.1%),2 (1.69%),5 (4.24%),14 (11.86%)
2,ARACATI,98,49 (50.0%),0 (0.0%),3 (3.06%),7 (7.14%),0 (0.0%),36 (36.73%),0 (0.0%),3 (3.06%),0 (0.0%)
4,BOA VIAGEM,95,34 (35.79%),6 (6.32%),1 (1.05%),0 (0.0%),16 (16.84%),35 (36.84%),1 (1.05%),2 (2.11%),0 (0.0%)
8,CEDRO,92,41 (44.57%),3 (3.26%),4 (4.35%),5 (5.43%),38 (41.3%),0 (0.0%),1 (1.09%),0 (0.0%),0 (0.0%)
9,CRATEUS,85,21 (24.71%),9 (10.59%),15 (17.65%),0 (0.0%),2 (2.35%),29 (34.12%),1 (1.18%),4 (4.71%),4 (4.71%)
1,ACARAU,83,10 (12.05%),25 (30.12%),1 (1.2%),0 (0.0%),6 (7.23%),12 (14.46%),0 (0.0%),22 (26.51%),7 (8.43%)
21,MARANGUAPE,80,36 (45.0%),1 (1.25%),11 (13.75%),0 (0.0%),7 (8.75%),4 (5.0%),1 (1.25%),19 (23.75%),1 (1.25%)
24,PARACURU,78,7 (8.97%),30 (38.46%),4 (5.13%),2 (2.56%),12 (15.38%),0 (0.0%),5 (6.41%),17 (21.79%),1 (1.28%)
25,PECÉM,73,11 (15.07%),0 (0.0%),0 (0.0%),0 (0.0%),56 (76.71%),0 (0.0%),0 (0.0%),6 (8.22%),0 (0.0%)
29,TABULEIRO,73,23 (31.51%),1 (1.37%),5 (6.85%),12 (16.44%),20 (27.4%),1 (1.37%),1 (1.37%),2 (2.74%),8 (10.96%)
0,ACOPIARA,72,17 (23.61%),17 (23.61%),6 (8.33%),12 (16.67%),0 (0.0%),3 (4.17%),1 (1.39%),9 (12.5%),7 (9.72%)
30,TAUA,69,15 (21.74%),0 (0.0%),8 (11.59%),1 (1.45%),6 (8.7%),11 (15.94%),1 (1.45%),3 (4.35%),24 (34.78%)
15,ITAPIPOCA,65,21 (32.31%),0 (0.0%),14 (21.54%),0 (0.0%),17 (26.15%),0 (0.0%),5 (7.69%),0 (0.0%),8 (12.31%)
5,CAMOCIM,60,15 (25.0%),13 (21.67%),7 (11.67%),4 (6.67%),11 (18.33%),0 (0.0%),0 (0.0%),2 (3.33%),8 (13.33%)
32,UBAJARA,56,18 (32.14%),1 (1.79%),7 (12.5%),1 (1.79%),0 (0.0%),21 (37.5%),0 (0.0%),4 (7.14%),4 (7.14%)
23,MORADA NOVA,52,16 (30.77%),0 (0.0%),1 (1.92%),0 (0.0%),17 (32.69%),8 (15.38%),10 (19.23%),0 (0.0%),0 (0.0%)
33,UMIRIM,51,11 (21.57%),1 (1.96%),12 (23.53%),0 (0.0%),0 (0.0%),7 (13.73%),2 (3.92%),0 (0.0%),18 (35.29%)
16,JAGUARIBE,48,10 (20.83%),10 (20.83%),0 (0.0%),1 (2.08%),22 (45.83%),0 (0.0%),0 (0.0%),5 (10.42%),0 (0.0%)
7,CAUCAIA,43,16 (37.21%),0 (0.0%),8 (18.6%),6 (13.95%),2 (4.65%),2 (4.65%),0 (0.0%),7 (16.28%),2 (4.65%)
3,BATURITE,42,0 (0.0%),0 (0.0%),9 (21.43%),12 (28.57%),0 (0.0%),11 (26.19%),0 (0.0%),6 (14.29%),4 (9.52%)
13,HORIZONTE,39,10 (25.64%),0 (0.0%),1 (2.56%),1 (2.56%),13 (33.33%),0 (0.0%),1 (2.56%),13 (33.33%),0 (0.0%)
17,JAGUARUANA,19,13 (68.42%),0 (0.0%),0 (0.0%),1 (5.26%),0 (0.0%),0 (0.0%),0 (0.0%),4 (21.05%),1 (5.26%)
12,GUARAMIRANGA,12,8 (66.67%),0 (0.0%),0 (0.0%),0 (0.0%),4 (33.33%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
27,REITORIA,9,5 (55.56%),0 (0.0%),0 (0.0%),1 (11.11%),1 (11.11%),1 (11.11%),0 (0.0%),0 (0.0%),1 (11.11%)
22,MOMBAÇA,2,0 (0.0%),0 (0.0%),0 (0.0%),1 (50.0%),1 (50.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

## Grande Área por Edital

In [21]:
analise_grande_area_por_edital = projetos_df.groupby("Grande Área de Conhecimento").agg(
    total_projetos=("ID do Projeto", "count"),
    total_externo=("Edital", lambda x: (x == "FOMENTO EXTERNO").sum()),
    total_pibic=("Edital", lambda x: (x == "PIBIC").sum()),
    total_pibic_af=("Edital", lambda x: (x == "PIBIC AF").sum()),
    total_pibic_jr=("Edital", lambda x: (x == "PIBIC JR").sum()),
    total_pibic_jr_af=("Edital", lambda x: (x == "PIBIC JR AF").sum()),
    total_pictv=("Edital", lambda x: (x == "PICTV").sum()),
    total_pibiti=("Edital", lambda x: (x == "PIBITI").sum())
).reset_index().rename(columns={
    "total_projetos": "Total de Projetos",
    "total_externo": "Fomento Externo",
    "total_pibic": "PIBIC",
    "total_pibic_af": "PIBIC AF",
    "total_pibic_jr": "PIBIC JR",
    "total_pibic_jr_af": "PIBIC JR AF",
    "total_pictv": "PICTV",
    "total_pibiti": "PIBITI"
})
analise_grande_area_por_edital = analise_grande_area_por_edital.sort_values(by="Total de Projetos", ascending=False)

analise_grande_area_por_edital['Fomento Externo'] = (
    analise_grande_area_por_edital['Fomento Externo'].astype(str) +
    ' (' + (analise_grande_area_por_edital['Fomento Externo'] / analise_grande_area_por_edital['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

analise_grande_area_por_edital['PIBIC'] = (
    analise_grande_area_por_edital['PIBIC'].astype(str) + 
    ' (' + (analise_grande_area_por_edital['PIBIC'] / analise_grande_area_por_edital['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

analise_grande_area_por_edital['PIBIC AF'] = (
    analise_grande_area_por_edital['PIBIC AF'].astype(str) +
    ' (' + (analise_grande_area_por_edital['PIBIC AF'] / analise_grande_area_por_edital['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

analise_grande_area_por_edital['PIBIC JR'] = (
    analise_grande_area_por_edital['PIBIC JR'].astype(str) +
    ' (' + (analise_grande_area_por_edital['PIBIC JR'] / analise_grande_area_por_edital['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

analise_grande_area_por_edital['PIBIC JR AF'] = (
    analise_grande_area_por_edital['PIBIC JR AF'].astype(str) +
    ' (' + (analise_grande_area_por_edital['PIBIC JR AF'] / analise_grande_area_por_edital['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

analise_grande_area_por_edital['PICTV'] = (
    analise_grande_area_por_edital['PICTV'].astype(str) +
    ' (' + (analise_grande_area_por_edital['PICTV'] / analise_grande_area_por_edital['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

analise_grande_area_por_edital['PIBITI'] = (
    analise_grande_area_por_edital['PIBITI'].astype(str) +
    ' (' + (analise_grande_area_por_edital['PIBITI'] / analise_grande_area_por_edital['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

display(analise_grande_area_por_edital)

,Grande Área de Conhecimento,Total de Projetos,Fomento Externo,PIBIC,PIBIC AF,PIBIC JR,PIBIC JR AF,PICTV,PIBITI
3,CIÊNCIAS EXATAS E DA TERRA,840,82 (9.76%),226 (26.9%),49 (5.83%),117 (13.93%),30 (3.57%),196 (23.33%),140 (16.67%)
6,ENGENHARIAS,685,40 (5.84%),206 (30.07%),45 (6.57%),122 (17.81%),22 (3.21%),113 (16.5%),137 (20.0%)
0,CIÊNCIAS AGRÁRIAS,624,13 (2.08%),215 (34.46%),72 (11.54%),88 (14.1%),27 (4.33%),73 (11.7%),136 (21.79%)
8,MULTIDISCIPLINAR,302,11 (3.64%),97 (32.12%),41 (13.58%),46 (15.23%),14 (4.64%),50 (16.56%),43 (14.24%)
4,CIÊNCIAS HUMANAS,294,7 (2.38%),96 (32.65%),34 (11.56%),34 (11.56%),20 (6.8%),82 (27.89%),21 (7.14%)
7,"LINGUÍSTICA, LETRAS E ARTES",178,6 (3.37%),77 (43.26%),12 (6.74%),16 (8.99%),4 (2.25%),57 (32.02%),6 (3.37%)
2,CIÊNCIAS DA SAÚDE,168,3 (1.79%),59 (35.12%),25 (14.88%),23 (13.69%),4 (2.38%),34 (20.24%),20 (11.9%)
1,CIÊNCIAS BIOLÓGICAS,143,5 (3.5%),49 (34.27%),18 (12.59%),13 (9.09%),3 (2.1%),42 (29.37%),13 (9.09%)
5,CIÊNCIAS SOCIAIS APLICADAS,139,9 (6.47%),45 (32.37%),14 (10.07%),22 (15.83%),9 (6.47%),30 (21.58%),10 (7.19%)

# Projetos por Área de Conhecimento ✅

## Total de Projetos por Área de Conhecimento

In [28]:
analise_area_conhecimento = projetos_df.groupby("Área de Conhecimento").agg(
    total_projetos=("Título do Projeto", "nunique"),
).reset_index().rename(columns={"total_projetos": "Total de Projetos"}).sort_values(by="Total de Projetos", ascending=False)

display(analise_area_conhecimento)

                          Área de Conhecimento  Total de Projetos
11                       CIÊNCIA DA COMPUTAÇÃO                421
30                         ENGENHARIA ELÉTRICA                231
1                                    AGRONOMIA                205
57                                     QUÍMICA                173
34                        ENGENHARIA SANITÁRIA                164
13           CIÊNCIA E TECNOLOGIA DE ALIMENTOS                160
20                                    EDUCAÇÃO                145
44                            INTERDISCIPLINAR                134
21                             EDUCAÇÃO FÍSICA                109
35                                      ENSINO                 89
26                            ENGENHARIA CIVIL                 87
65                                   ZOOTECNIA                 84
45                                      LETRAS                 60
47                                  MATEMÁTICA                 58
42                                   GEOGRAFIA                 54
46                                 LINGUÍSTICA                 48
4                                        ARTES                 44
39                                      FÍSICA                 42
0                                ADMINISTRAÇÃO                 41
59   RECURSOS PESQUEIROS E ENGENHARIA DE PESCA                 40
50                               MICROBIOLOGIA                 32
31                         ENGENHARIA MECÂNICA                 31
9                                BIOTECNOLOGIA                 29
24                         ENGENHARIA AGRÍCOLA                 27
27       ENGENHARIA DE MATERIAIS E METALÚRGICA                 24
52                                    NUTRIÇÃO                 23
7                               BIOLOGIA GERAL                 22
18                                    ECOLOGIA                 21
49                        MEDICINA VETERINÁRIA                 18
3                      ARQUITETURA E URBANISMO                 16
28                      ENGENHARIA DE PRODUÇÃO                 16
5                                   ASTRONOMIA                 15
10                                    BOTÂNICA                 15
19                                    ECONOMIA                 14
60                              SAÚDE COLETIVA                 14
37                                   FILOSOFIA                 14
41                                 GEOCIÊNCIAS                 12
12                       CIÊNCIA DA INFORMAÇÃO                 12
61                             SERVIÇO SOCIAL                 11
43                                    HISTÓRIA                 11
64                                    ZOOLOGIA                  9
48                                   MATERIAIS                  9
8                                   BIOQUÍMICA                  9
62                                  SOCIOLOGIA                  9
63                                     TURISMO                  9
29                   ENGENHARIA DE TRANSPORTES                  7
38                                  FISIOLOGIA                  6
36                                FARMACOLOGIA                  5
25                        ENGENHARIA BIOMÉDICA                  5
33                          ENGENHARIA QUÍMICA                  5
58  RECURSOS FLORESTAIS E ENGENHARIA FLORESTAL                  5
40                                    GENÉTICA                  5
17                                     DIREITO                  4
2                                 ANTROPOLOGIA                  4
23                     ENGENHARIA AEROESPACIAL                  3
32                 ENGENHARIA NAVAL E OCEÃNICA                  2
15                                 COMUNICAÇÃO                  2
55                 PROBABILIDADE E ESTATÍSTICA                  2
56                                  PSICOLOGIA                  2
6                                    BIOFÍSICA                  1
14                            CIÊNCIA POLÍTICA                  1
16                          DESENHO INDUSTRIAL                  1
22                                  ENFERMAGEM                  1
54              PLANEJAMENTO URBANO E REGIONAL                  1
51                                  MORFOLOGIA                  1
53                               PARASITOLOGIA                  1

## Área de Conhecimento Predominante por Campus

In [ ]:
analise_area_conhecimento_por_campus = (
    projetos_df
    .groupby(["Campus", "Área de Conhecimento"])
    .agg(total_projetos=("Título do Projeto", "count"))
    .reset_index()
    .rename(columns={"total_projetos": "Total de Projetos"})
    .sort_values(["Campus", "Total de Projetos"], ascending=[True, False])
)

analise_area_conhecimento_por_campus = (
    analise_area_conhecimento_por_campus
    .loc[analise_area_conhecimento_por_campus.groupby("Campus")["Total de Projetos"].idxmax()]
    .reset_index(drop=True)
)

display(analise_area_conhecimento_por_campus)

## Tipo de Edital por Área de Conhecimento

In [31]:
analise_edital_por_area_conhecimento = projetos_df.groupby("Área de Conhecimento").agg(
    total_projetos=("Título do Projeto", "count"),
    total_externo=("Edital", lambda x: (x == "FOMENTO EXTERNO").sum()),
    total_pibic=("Edital", lambda x: (x == "PIBIC").sum()),
    total_pibic_af=("Edital", lambda x: (x == "PIBIC AF").sum()),
    total_pibic_jr=("Edital", lambda x: (x == "PIBIC JR").sum()),
    total_pibic_jr_af=("Edital", lambda x: (x == "PIBIC JR AF").sum()),
    total_pictv=("Edital", lambda x: (x == "PICTV").sum()),
    total_pibiti=("Edital", lambda x: (x == "PIBITI").sum())
).reset_index().rename(columns={
    "total_projetos": "Total de Projetos",
    "total_externo": "Fomento Externo",
    "total_pibic": "PIBIC",
    "total_pibic_af": "PIBIC AF",
    "total_pibic_jr": "PIBIC JR",
    "total_pibic_jr_af": "PIBIC JR AF",
    "total_pictv": "PICTV",
    "total_pibiti": "PIBITI"
}).sort_values(by="Total de Projetos", ascending=False)

analise_edital_por_area_conhecimento['Fomento Externo'] = (
    analise_edital_por_area_conhecimento['Fomento Externo'].astype(str) +
    " (" + (analise_edital_por_area_conhecimento['Fomento Externo'] / analise_edital_por_area_conhecimento['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

analise_edital_por_area_conhecimento['PIBIC'] = (
    analise_edital_por_area_conhecimento['PIBIC'].astype(str) +
      " (" + (analise_edital_por_area_conhecimento['PIBIC'] / analise_edital_por_area_conhecimento['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)  

analise_edital_por_area_conhecimento['PIBIC AF'] = (
    analise_edital_por_area_conhecimento['PIBIC AF'].astype(str) + 
    " (" + (analise_edital_por_area_conhecimento['PIBIC AF'] / analise_edital_por_area_conhecimento['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

analise_edital_por_area_conhecimento['PIBIC JR'] = (
    analise_edital_por_area_conhecimento['PIBIC JR'].astype(str) + 
    " (" + (analise_edital_por_area_conhecimento['PIBIC JR'] / analise_edital_por_area_conhecimento['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

analise_edital_por_area_conhecimento['PIBIC JR AF'] = (
    analise_edital_por_area_conhecimento['PIBIC JR AF'].astype(str) +
      " (" + (analise_edital_por_area_conhecimento['PIBIC JR AF'] / analise_edital_por_area_conhecimento['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

analise_edital_por_area_conhecimento['PICTV'] = (
    analise_edital_por_area_conhecimento['PICTV'].astype(str) + " (" +
      (analise_edital_por_area_conhecimento['PICTV'] / analise_edital_por_area_conhecimento['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

analise_edital_por_area_conhecimento['PIBITI'] = (
    analise_edital_por_area_conhecimento['PIBITI'].astype(str) + " (" +
      (analise_edital_por_area_conhecimento['PIBITI'] / analise_edital_por_area_conhecimento['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

display(analise_edital_por_area_conhecimento)

,Área de Conhecimento,Total de Projetos,Fomento Externo,PIBIC,PIBIC AF,PIBIC JR,PIBIC JR AF,PICTV,PIBITI
11,CIÊNCIA DA COMPUTAÇÃO,483,72 (14.91%),109 (22.57%),32 (6.63%),56 (11.59%),12 (2.48%),109 (22.57%),93 (19.25%)
30,ENGENHARIA ELÉTRICA,293,24 (8.19%),87 (29.69%),15 (5.12%),56 (19.11%),11 (3.75%),27 (9.22%),73 (24.91%)
1,AGRONOMIA,225,4 (1.78%),78 (34.67%),35 (15.56%),35 (15.56%),7 (3.11%),24 (10.67%),42 (18.67%)
57,QUÍMICA,192,4 (2.08%),56 (29.17%),9 (4.69%),37 (19.27%),14 (7.29%),43 (22.4%),29 (15.1%)
13,CIÊNCIA E TECNOLOGIA DE ALIMENTOS,188,0 (0.0%),64 (34.04%),19 (10.11%),21 (11.17%),9 (4.79%),17 (9.04%),58 (30.85%)
34,ENGENHARIA SANITÁRIA,185,2 (1.08%),64 (34.59%),14 (7.57%),31 (16.76%),6 (3.24%),30 (16.22%),38 (20.54%)
20,EDUCAÇÃO,181,5 (2.76%),64 (35.36%),20 (11.05%),15 (8.29%),8 (4.42%),57 (31.49%),12 (6.63%)
44,INTERDISCIPLINAR,152,5 (3.29%),47 (30.92%),24 (15.79%),23 (15.13%),8 (5.26%),13 (8.55%),32 (21.05%)
21,EDUCAÇÃO FÍSICA,125,3 (2.4%),46 (36.8%),20 (16.0%),18 (14.4%),2 (1.6%),20 (16.0%),16 (12.8%)
65,ZOOTECNIA,103,5 (4.85%),33 (32.04%),10 (9.71%),19 (18.45%),8 (7.77%),16 (15.53%),12 (11.65%)
35,ENSINO,100,5 (5.0%),35 (35.0%),14 (14.0%),10 (10.0%),4 (4.0%),28 (28.0%),4 (4.0%)
26,ENGENHARIA CIVIL,97,5 (5.15%),27 (27.84%),6 (6.19%),13 (13.4%),3 (3.09%),35 (36.08%),8 (8.25%)
47,MATEMÁTICA,77,0 (0.0%),37 (48.05%),6 (7.79%),7 (9.09%),2 (2.6%),20 (25.97%),5 (6.49%)
45,LETRAS,73,0 (0.0%),34 (46.58%),6 (8.22%),7 (9.59%),2 (2.74%),21 (28.77%),3 (4.11%)
42,GEOGRAFIA,66,1 (1.52%),22 (33.33%),6 (9.09%),10 (15.15%),8 (12.12%),11 (16.67%),8 (12.12%)
46,LINGUÍSTICA,57,2 (3.51%),20 (35.09%),4 (7.02%),6 (10.53%),2 (3.51%),21 (36.84%),2 (3.51%)
39,FÍSICA,54,2 (3.7%),15 (27.78%),1 (1.85%),9 (16.67%),1 (1.85%),18 (33.33%),8 (14.81%)
0,ADMINISTRAÇÃO,51,4 (7.84%),18 (35.29%),0 (0.0%),12 (23.53%),4 (7.84%),11 (21.57%),2 (3.92%)
4,ARTES,48,4 (8.33%),23 (47.92%),2 (4.17%),3 (6.25%),0 (0.0%),15 (31.25%),1 (2.08%)
59,RECURSOS PESQUEIROS E ENGENHARIA DE PESCA,48,3 (6.25%),17 (35.42%),4 (8.33%),6 (12.5%),1 (2.08%),11 (22.92%),6 (12.5%)
24,ENGENHARIA AGRÍCOLA,35,1 (2.86%),14 (40.0%),1 (2.86%),5 (14.29%),0 (0.0%),3 (8.57%),11 (31.43%)
9,BIOTECNOLOGIA,34,0 (0.0%),13 (38.24%),3 (8.82%),3 (8.82%),1 (2.94%),8 (23.53%),6 (17.65%)
50,MICROBIOLOGIA,34,2 (5.88%),15 (44.12%),6 (17.65%),0 (0.0%),0 (0.0%),8 (23.53%),3 (8.82%)
31,ENGENHARIA MECÂNICA,33,4 (12.12%),7 (21.21%),3 (9.09%),12 (36.36%),1 (3.03%),2 (6.06%),4 (12.12%)
27,ENGENHARIA DE MATERIAIS E METALÚRGICA,32,2 (6.25%),6 (18.75%),4 (12.5%),6 (18.75%),1 (3.12%),8 (25.0%),5 (15.62%)
7,BIOLOGIA GERAL,24,1 (4.17%),3 (12.5%),3 (12.5%),7 (29.17%),0 (0.0%),9 (37.5%),1 (4.17%)
18,ECOLOGIA,23,2 (8.7%),7 (30.43%),5 (21.74%),2 (8.7%),1 (4.35%),6 (26.09%),0 (0.0%)
49,MEDICINA VETERINÁRIA,23,0 (0.0%),6 (26.09%),3 (13.04%),2 (8.7%),2 (8.7%),5 (21.74%),5 (21.74%)
52,NUTRIÇÃO,23,0 (0.0%),9 (39.13%),1 (4.35%),3 (13.04%),0 (0.0%),9 (39.13%),1 (4.35%)
28,ENGENHARIA DE PRODUÇÃO,22,1 (4.55%),9 (40.91%),1 (4.55%),0 (0.0%),0 (0.0%),6 (27.27%),5 (22.73%)
3,ARQUITETURA E URBANISMO,21,0 (0.0%),5 (23.81%),3 (14.29%),1 (4.76%),1 (4.76%),8 (38.1%),3 (14.29%)
19,ECONOMIA,20,3 (15.0%),5 (25.0%),2 (10.0%),6 (30.0%),0 (0.0%),2 (10.0%),2 (10.0%)
60,SAÚDE COLETIVA,19,0 (0.0%),4 (21.05%),4 (21.05%),2 (10.53%),2 (10.53%),5 (26.32%),2 (10.53%)
10,BOTÂNICA,17,0 (0.0%),5 (29.41%),0 (0.0%),1 (5.88%),1 (5.88%),5 (29.41%),5 (29.41%)
8,BIOQUÍMICA,16,0 (0.0%),5 (31.25%),1 (6.25%),1 (6.25%),1 (6.25%),5 (31.25%),3 (18.75%)
5,ASTRONOMIA,16,2 (12.5%),3 (18.75%),1 (6.25%),4 (25.0%),1 (6.25%),2 (12.5%),3 (18.75%)
48,MATERIAIS,16,1 (6.25%),2 (12.5%),0 (0.0%),10 (62.5%),1 (6.25%),1 (6.25%),1 (6.25%)
41,GEOCIÊNCIAS,15,1 (6.67%),4 (26.67%),0 (0.0%),4 (26.67%),0 (0.0%),4 (26.67%),2 (13.33%)
61,SERVIÇO SOCIAL,15,0 (0.0%),8 (53.33%),7 (46.67%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
37,FILOSOFIA,15,0 (0.0%),4 (26.67%),2 (13.33%),5 (33.33%),1 (6.67%),3 (20.0%),0 (0.0%)
12,CIÊNCIA DA INFORMAÇÃO,14,1 (7.14%),3 (21.43%),1 (7.14%),0 (0.0%),3 (21.43%),5 (35.71%),1 (7.14%)
62,SOCIOLOGIA,12,0 (0.0%),4 (33.33%),4 (33.33%),0 (0.0%),1 (8.33%),2 (16.67%),1 (8.33%)
43,HISTÓRIA,11,1 (9.09%),0 (0.0%),0 (0.0%),2 (18.18%),1 (9.09%),7 (63.64%),0 (0.0%)
64,ZOOLOGIA,10,0 (0.0%),6 (60.0%),0 (0.0%),0 (0.0%),0 (0.0%),4 (40.0%),0 (0.0%)
63,TURISMO,9,0 (0.0%),6 (66.67%),1 (11.11%),0 (0.0%),0 (0.0%),1 (11.11%),1 (11.11%)
29,ENGENHARIA DE TRANSPORTES,7,0 (0.0%),1 (14.29%),1 (14.29%),2 (28.57%),0 (0.0%),2 (28.57%),1 (14.29%)
25,ENGENHARIA BIOMÉDICA,6,1 (16.67%),3 (50.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),2 (33.33%)
33,ENGENHARIA QUÍMICA,6,0 (0.0%),1 (16.67%),0 (0.0%),2 (33.33%),0 (0.0%),2 (33.33%),1 (16.67%)
2,ANTROPOLOGIA,6,0 (0.0%),1 (16.67%),1 (16.67%),1 (16.67%),1 (16.67%),2 (33.33%),0 (0.0%)
38,FISIOLOGIA,6,0 (0.0%),1 (16.67%),1 (16.67%),1 (16.67%),0 (0.0%),3 (50.0%),0 (0.0%)
36,FARMACOLOGIA,5,0 (0.0%),4 (80.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (20.0%),0 (0.0%)
40,GENÉTICA,5,0 (0.0%),3 (60.0%),1 (20.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (20.0%)
58,RECURSOS FLORESTAIS E ENGENHARIA FLORESTAL,5,0 (0.0%),3 (60.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),2 (40.0%)
17,DIREITO,4,1 (25.0%),0 (0.0%),0 (0.0%),1 (25.0%),0 (0.0%),1 (25.0%),1 (25.0%)
23,ENGENHARIA AEROESPACIAL,3,0 (0.0%),1 (33.33%),1 (33.33%),0 (0.0%),0 (0.0%),1 (33.33%),0 (0.0%)
55,PROBABILIDADE E ESTATÍSTICA,3,1 (33.33%),2 (66.67%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
16,DESENHO INDUSTRIAL,2,0 (0.0%),0 (0.0%),0 (0.0%),1 (50.0%),0 (0.0%),1 (50.0%),0 (0.0%)
15,COMUNICAÇÃO,2,0 (0.0%),0 (0.0%),0 (0.0%),1 (50.0%),1 (50.0%),0 (0.0%),0 (0.0%)
56,PSICOLOGIA,2,0 (0.0%),1 (50.0%),0 (0.0%),1 (50.0%),0 (0.0%),0 (0.0%),0 (0.0%)
32,ENGENHARIA NAVAL E OCEÃNICA,2,1 (50.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (50.0%),0 (0.0%)
6,BIOFÍSICA,1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (100.0%),0 (0.0%)
14,CIÊNCIA POLÍTICA,1,0 (0.0%),0 (0.0%),1 (100.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
22,ENFERMAGEM,1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (100.0%)
54,PLANEJAMENTO URBANO E REGIONAL,1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (100.0%),0 (0.0%)
51,MORFOLOGIA,1,0 (0.0%),0 (0.0%),1 (100.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
53,PARASITOLOGIA,1,0 (0.0%),0 (0.0%),0 (0.0%),1 (100.0%),0 (0.0%),0 (0.0%),0 (0.0%)

# Pesquisadores

## Pesquisadores por Ano

In [40]:
analise_pesquisadores_ano = membros_projetos_df.groupby("Ano de Início da Execução").agg(
    total_pesquisadores=("Nome do Membro", "count"),
    bolsistas=("Vínculo com Projeto", lambda x: (x == "Bolsista").sum()),
    voluntarios=("Vínculo com Projeto", lambda x: (x == "Voluntário").sum()),
).reset_index().rename(columns={"total_pesquisadores": "Total de Pesquisadores", "bolsistas": "Bolsistas", "voluntarios": "Voluntários"})

analise_pesquisadores_ano['Bolsistas'] = (
    analise_pesquisadores_ano['Bolsistas'].astype(str) +
    ' (' + (analise_pesquisadores_ano['Bolsistas'] / analise_pesquisadores_ano['Total de Pesquisadores'] * 100).round(2).astype(str) + '%)'
)

analise_pesquisadores_ano['Voluntários'] = (
    analise_pesquisadores_ano['Voluntários'].astype(str) +
    ' (' + (analise_pesquisadores_ano['Voluntários'] / analise_pesquisadores_ano['Total de Pesquisadores'] * 100).round(2).astype(str) + '%)'
)

display(analise_pesquisadores_ano)

,Ano de Início da Execução,Total de Pesquisadores,Bolsistas,Voluntários
0,2014.0,1,0 (0.0%),1 (100.0%)
1,2022.0,20,12 (60.0%),8 (40.0%)
2,2023.0,2025,614 (30.32%),1411 (69.68%)
3,2024.0,2133,648 (30.38%),1485 (69.62%)
4,2025.0,2959,847 (28.62%),2112 (71.38%)
5,2026.0,190,17 (8.95%),173 (91.05%)

## Pesquisadores por Edital

In [42]:
analise_pesquisadores_edital = membros_projetos_df.groupby("Categoria do Membro").agg(
    total_projetos=("ID do Projeto", "count"),
    total_externo=("Edital", lambda x: (x == "FOMENTO EXTERNO").sum()),
    total_pibic=("Edital", lambda x: (x == "PIBIC").sum()),
    total_pibic_af=("Edital", lambda x: (x == "PIBIC AF").sum()),
    total_pibic_jr=("Edital", lambda x: (x == "PIBIC JR").sum()),
    total_pibic_jr_af=("Edital", lambda x: (x == "PIBIC JR AF").sum()),
    total_pictv=("Edital", lambda x: (x == "PICTV").sum()),
    total_pibiti=("Edital", lambda x: (x == "PIBITI").sum())
).reset_index().rename(columns={
    "total_projetos": "Total de Projetos",
    "total_externo": "Fomento Externo",
    "total_pibic": "PIBIC",
    "total_pibic_af": "PIBIC AF",
    "total_pibic_jr": "PIBIC JR",
    "total_pibic_jr_af": "PIBIC JR AF",
    "total_pictv": "PICTV",
    "total_pibiti": "PIBITI"
})
analise_pesquisadores_edital = analise_pesquisadores_edital.sort_values(by="Total de Projetos", ascending=False)

analise_pesquisadores_edital['Fomento Externo'] = (
    analise_pesquisadores_edital['Fomento Externo'].astype(str) +
    ' (' + (analise_pesquisadores_edital['Fomento Externo'] / analise_pesquisadores_edital['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

analise_pesquisadores_edital['PIBIC'] = (
    analise_pesquisadores_edital['PIBIC'].astype(str) + 
    ' (' + (analise_pesquisadores_edital['PIBIC'] / analise_pesquisadores_edital['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

analise_pesquisadores_edital['PIBIC AF'] = (
    analise_pesquisadores_edital['PIBIC AF'].astype(str) +
    ' (' + (analise_pesquisadores_edital['PIBIC AF'] / analise_pesquisadores_edital['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

analise_pesquisadores_edital['PIBIC JR'] = (
    analise_pesquisadores_edital['PIBIC JR'].astype(str) +
    ' (' + (analise_pesquisadores_edital['PIBIC JR'] / analise_pesquisadores_edital['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

analise_pesquisadores_edital['PIBIC JR AF'] = (
    analise_pesquisadores_edital['PIBIC JR AF'].astype(str) +
    ' (' + (analise_pesquisadores_edital['PIBIC JR AF'] / analise_pesquisadores_edital['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

analise_pesquisadores_edital['PICTV'] = (
    analise_pesquisadores_edital['PICTV'].astype(str) +
    ' (' + (analise_pesquisadores_edital['PICTV'] / analise_pesquisadores_edital['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

analise_pesquisadores_edital['PIBITI'] = (
    analise_pesquisadores_edital['PIBITI'].astype(str) +
    ' (' + (analise_pesquisadores_edital['PIBITI'] / analise_pesquisadores_edital['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

display(analise_pesquisadores_edital)

,Categoria do Membro,Total de Projetos,Fomento Externo,PIBIC,PIBIC AF,PIBIC JR,PIBIC JR AF,PICTV,PIBITI
1,Docente,4083,679 (16.63%),1097 (26.87%),314 (7.69%),509 (12.47%),134 (3.28%),799 (19.57%),551 (13.49%)
0,Discente,2923,276 (9.44%),590 (20.18%),95 (3.25%),322 (11.02%),90 (3.08%),1264 (43.24%),286 (9.78%)
3,TAE,234,94 (40.17%),38 (16.24%),12 (5.13%),16 (6.84%),12 (5.13%),51 (21.79%),11 (4.7%)
2,Não Informado,88,38 (43.18%),3 (3.41%),0 (0.0%),17 (19.32%),5 (5.68%),23 (26.14%),2 (2.27%)

## Pesquisadores por Área de Conhecimento

In [43]:
analise_pesquisadores_area_conhecimento = membros_projetos_df.groupby("Área de Conhecimento").agg(
    total_projetos=("ID do Projeto", "count"),
    discente=("Categoria do Membro", lambda x: (x == "Discente").sum()),
    docente=("Categoria do Membro", lambda x: (x == "Docente").sum()),
    tae=("Categoria do Membro", lambda x: (x == "TAE").sum()),
    outros=("Categoria do Membro", lambda x: (x == "Não Informado").sum())
).reset_index().rename(columns={
    "total_projetos": "Total de Projetos",
    "discente": "Discente",
    "docente": "Docente",
    "tae": "TAE",
    "outros": "Não Informado"
}).sort_values(by="Total de Projetos", ascending=False)

analise_pesquisadores_area_conhecimento['Discente'] = (
    analise_pesquisadores_area_conhecimento['Discente'].astype(str) +
    ' (' + (analise_pesquisadores_area_conhecimento['Discente'] / analise_pesquisadores_area_conhecimento['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

analise_pesquisadores_area_conhecimento['Docente'] = (
    analise_pesquisadores_area_conhecimento['Docente'].astype(str) +
    ' (' + (analise_pesquisadores_area_conhecimento['Docente'] / analise_pesquisadores_area_conhecimento['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

analise_pesquisadores_area_conhecimento['TAE'] = (
    analise_pesquisadores_area_conhecimento['TAE'].astype(str) +
    ' (' + (analise_pesquisadores_area_conhecimento['TAE'] / analise_pesquisadores_area_conhecimento['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

analise_pesquisadores_area_conhecimento['Não Informado'] = (
    analise_pesquisadores_area_conhecimento['Não Informado'].astype(str) +
    ' (' + (analise_pesquisadores_area_conhecimento['Não Informado'] / analise_pesquisadores_area_conhecimento['Total de Projetos'] * 100).round(2).astype(str) + '%)'
)

display(analise_pesquisadores_area_conhecimento)

,Área de Conhecimento,Total de Projetos,Discente,Docente,TAE,Não Informado
11,CIÊNCIA DA COMPUTAÇÃO,1462,555 (37.96%),793 (54.24%),81 (5.54%),33 (2.26%)
30,ENGENHARIA ELÉTRICA,657,193 (29.38%),442 (67.28%),13 (1.98%),9 (1.37%)
1,AGRONOMIA,437,171 (39.13%),238 (54.46%),21 (4.81%),7 (1.6%)
57,QUÍMICA,387,155 (40.05%),214 (55.3%),15 (3.88%),3 (0.78%)
34,ENGENHARIA SANITÁRIA,385,168 (43.64%),194 (50.39%),17 (4.42%),6 (1.56%)
20,EDUCAÇÃO,363,160 (44.08%),198 (54.55%),5 (1.38%),0 (0.0%)
13,CIÊNCIA E TECNOLOGIA DE ALIMENTOS,351,131 (37.32%),211 (60.11%),7 (1.99%),2 (0.57%)
44,INTERDISCIPLINAR,293,121 (41.3%),170 (58.02%),2 (0.68%),0 (0.0%)
21,EDUCAÇÃO FÍSICA,230,90 (39.13%),140 (60.87%),0 (0.0%),0 (0.0%)
35,ENSINO,225,99 (44.0%),123 (54.67%),1 (0.44%),2 (0.89%)
26,ENGENHARIA CIVIL,219,108 (49.32%),109 (49.77%),1 (0.46%),1 (0.46%)
65,ZOOTECNIA,208,68 (32.69%),123 (59.13%),16 (7.69%),1 (0.48%)
45,LETRAS,132,54 (40.91%),77 (58.33%),1 (0.76%),0 (0.0%)
47,MATEMÁTICA,131,47 (35.88%),84 (64.12%),0 (0.0%),0 (0.0%)
46,LINGUÍSTICA,128,69 (53.91%),58 (45.31%),0 (0.0%),1 (0.78%)
42,GEOGRAFIA,119,48 (40.34%),69 (57.98%),1 (0.84%),1 (0.84%)
0,ADMINISTRAÇÃO,113,45 (39.82%),56 (49.56%),8 (7.08%),4 (3.54%)
4,ARTES,113,59 (52.21%),51 (45.13%),2 (1.77%),1 (0.88%)
59,RECURSOS PESQUEIROS E ENGENHARIA DE PESCA,102,52 (50.98%),47 (46.08%),1 (0.98%),2 (1.96%)
39,FÍSICA,98,37 (37.76%),60 (61.22%),0 (0.0%),1 (1.02%)
31,ENGENHARIA MECÂNICA,87,32 (36.78%),51 (58.62%),4 (4.6%),0 (0.0%)
50,MICROBIOLOGIA,71,34 (47.89%),34 (47.89%),3 (4.23%),0 (0.0%)
9,BIOTECNOLOGIA,61,19 (31.15%),31 (50.82%),11 (18.03%),0 (0.0%)
52,NUTRIÇÃO,61,34 (55.74%),23 (37.7%),0 (0.0%),4 (6.56%)
49,MEDICINA VETERINÁRIA,59,36 (61.02%),23 (38.98%),0 (0.0%),0 (0.0%)
24,ENGENHARIA AGRÍCOLA,59,19 (32.2%),38 (64.41%),2 (3.39%),0 (0.0%)
27,ENGENHARIA DE MATERIAIS E METALÚRGICA,54,20 (37.04%),33 (61.11%),0 (0.0%),1 (1.85%)
7,BIOLOGIA GERAL,53,22 (41.51%),29 (54.72%),2 (3.77%),0 (0.0%)
18,ECOLOGIA,49,22 (44.9%),25 (51.02%),2 (4.08%),0 (0.0%)
60,SAÚDE COLETIVA,48,26 (54.17%),19 (39.58%),2 (4.17%),1 (2.08%)
28,ENGENHARIA DE PRODUÇÃO,41,18 (43.9%),23 (56.1%),0 (0.0%),0 (0.0%)
10,BOTÂNICA,38,18 (47.37%),18 (47.37%),2 (5.26%),0 (0.0%)
43,HISTÓRIA,37,23 (62.16%),14 (37.84%),0 (0.0%),0 (0.0%)
3,ARQUITETURA E URBANISMO,37,16 (43.24%),21 (56.76%),0 (0.0%),0 (0.0%)
41,GEOCIÊNCIAS,33,13 (39.39%),20 (60.61%),0 (0.0%),0 (0.0%)
61,SERVIÇO SOCIAL,31,13 (41.94%),17 (54.84%),1 (3.23%),0 (0.0%)
5,ASTRONOMIA,31,13 (41.94%),18 (58.06%),0 (0.0%),0 (0.0%)
19,ECONOMIA,30,8 (26.67%),21 (70.0%),0 (0.0%),1 (3.33%)
12,CIÊNCIA DA INFORMAÇÃO,26,8 (30.77%),8 (30.77%),9 (34.62%),1 (3.85%)
37,FILOSOFIA,25,10 (40.0%),15 (60.0%),0 (0.0%),0 (0.0%)
8,BIOQUÍMICA,22,6 (27.27%),16 (72.73%),0 (0.0%),0 (0.0%)
48,MATERIAIS,22,5 (22.73%),16 (72.73%),1 (4.55%),0 (0.0%)
38,FISIOLOGIA,20,11 (55.0%),6 (30.0%),0 (0.0%),3 (15.0%)
33,ENGENHARIA QUÍMICA,20,12 (60.0%),5 (25.0%),2 (10.0%),1 (5.0%)
29,ENGENHARIA DE TRANSPORTES,18,8 (44.44%),9 (50.0%),1 (5.56%),0 (0.0%)
64,ZOOLOGIA,18,7 (38.89%),11 (61.11%),0 (0.0%),0 (0.0%)
62,SOCIOLOGIA,15,2 (13.33%),13 (86.67%),0 (0.0%),0 (0.0%)
25,ENGENHARIA BIOMÉDICA,14,5 (35.71%),8 (57.14%),0 (0.0%),1 (7.14%)
36,FARMACOLOGIA,14,7 (50.0%),7 (50.0%),0 (0.0%),0 (0.0%)
63,TURISMO,12,2 (16.67%),10 (83.33%),0 (0.0%),0 (0.0%)
40,GENÉTICA,11,4 (36.36%),7 (63.64%),0 (0.0%),0 (0.0%)
58,RECURSOS FLORESTAIS E ENGENHARIA FLORESTAL,10,5 (50.0%),5 (50.0%),0 (0.0%),0 (0.0%)
2,ANTROPOLOGIA,9,3 (33.33%),6 (66.67%),0 (0.0%),0 (0.0%)
17,DIREITO,8,4 (50.0%),4 (50.0%),0 (0.0%),0 (0.0%)
23,ENGENHARIA AEROESPACIAL,5,2 (40.0%),3 (60.0%),0 (0.0%),0 (0.0%)
55,PROBABILIDADE E ESTATÍSTICA,4,1 (25.0%),3 (75.0%),0 (0.0%),0 (0.0%)
56,PSICOLOGIA,4,2 (50.0%),2 (50.0%),0 (0.0%),0 (0.0%)
15,COMUNICAÇÃO,3,1 (33.33%),2 (66.67%),0 (0.0%),0 (0.0%)
16,DESENHO INDUSTRIAL,3,0 (0.0%),2 (66.67%),0 (0.0%),1 (33.33%)
54,PLANEJAMENTO URBANO E REGIONAL,3,1 (33.33%),2 (66.67%),0 (0.0%),0 (0.0%)
6,BIOFÍSICA,2,0 (0.0%),2 (100.0%),0 (0.0%),0 (0.0%)
32,ENGENHARIA NAVAL E OCEÃNICA,2,0 (0.0%),2 (100.0%),0 (0.0%),0 (0.0%)
51,MORFOLOGIA,2,1 (50.0%),1 (50.0%),0 (0.0%),0 (0.0%)
14,CIÊNCIA POLÍTICA,1,0 (0.0%),1 (100.0%),0 (0.0%),0 (0.0%)
22,ENFERMAGEM,1,0 (0.0%),1 (100.0%),0 (0.0%),0 (0.0%)
53,PARASITOLOGIA,1,0 (0.0%),1 (100.0%),0 (0.0%),0 (0.0%)

# Grupos de Pesquisa

In [16]:
total_grupos_de_pesquisa = grupos_pesquisa_df["Nome do Grupo de Pesquisa"].nunique()
print(f"Total de Grupos de Pesquisa: {total_grupos_de_pesquisa}")

total_projetos_grupo_pesquisa = grupos_pesquisa_df["Total de Projetos Aprovados"].sum()
print(f"Total de Projetos Aprovados em Grupos de Pesquisa: {total_projetos_grupo_pesquisa}")

Total de Grupos de Pesquisa: 174
Total de Projetos Aprovados em Grupos de Pesquisa: 1667

# Produção Técnica

In [ ]:
total_producoes_tecnicas = producoes_tecnicas_df.shape[0]
print(f"Total de Produções Técnicas: {total_producoes_tecnicas}")

analise_producoes_tecnicas_por_tipo = producoes_tecnicas_df.loc[:, ["Tipo de Publicação", "ID"]]
analise_producoes_tecnicas_por_tipo = analise_producoes_tecnicas_por_tipo.groupby("Tipo de Publicação").count().reset_index()
analise_producoes_tecnicas_por_tipo = analise_producoes_tecnicas_por_tipo.rename(columns={
    "ID": "Total de Produções Técnicas"
})
analise_producoes_tecnicas_por_tipo = analise_producoes_tecnicas_por_tipo.sort_values(by="Total de Produções Técnicas", ascending=False)
analise_producoes_tecnicas_por_tipo["Total de Produções Técnicas"] = (
    analise_producoes_tecnicas_por_tipo["Total de Produções Técnicas"].astype(str)
    + " ("
    + (
        analise_producoes_tecnicas_por_tipo["Total de Produções Técnicas"].astype(int)
        / total_producoes_tecnicas * 100
    ).round(2).astype(str)
    + "%)"
)
display(analise_producoes_tecnicas_por_tipo)

Total de Produções Técnicas: 82177

,Tipo de Publicação,Total de Produções Técnicas
0,Apresentação De Trabalho,35683 (43.42%)
8,Organização De Evento,16275 (19.8%)
2,Curso De Curta Duração Ministrado,10433 (12.7%)
16,Trabalho Tecnico,8208 (9.99%)
13,Programa De Radio Ou Tv,3006 (3.66%)
9,Outra Produção Tecnica,2414 (2.94%)
3,Desenvolvimento De Material Didatico Ou Instrucional,2275 (2.77%)
15,Software,1034 (1.26%)
14,Relatorio De Pesquisa,730 (0.89%)
10,Patente,542 (0.66%)
12,Produto Tecnologico,511 (0.62%)
4,Editoração,432 (0.53%)
11,Processos Ou Tecnicas,346 (0.42%)
1,Carta Mapa Ou Similar,213 (0.26%)
7,Marca,49 (0.06%)
6,Maquete,24 (0.03%)
5,Manutenção De Obra Artistica,2 (0.0%)

# Orientações

# Destaques